language: php

matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: nightly
    fast_finish: true
    allow_failures:
        - php: nightly

sudo: false

cache:
  directories:
    - $HOME/.composer

install:
  - composer install --prefer-source

script:
  - make travis

after_success:
  - bash <(curl -s https://codecov.io/bash)
